# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Le4sR930TLn2PK2pfg-hzcFCiv0AmUHy
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

#load the car dataset
df=pd.read_csv("car_dataset.csv")
df['class'] = df['class'].map({0: 'unacc', 1: 'acc', 2: 'good', 3: 'vgood'})

# Train a Logistic Regression model (softmax)
x = df.drop('class', axis=1)
y = df['class']
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)
model.fit(x, y)

# Streamlit app
st.title('Car Evaluation')
st.write("Predict the evaluation of cars based on its features")

# User inputs
buying = st.selectbox('buying', df['buying'].unique())
maint = st.selectbox('maint', df['maint'].unique())
doors = st.selectbox('doors', df['doors'].unique())
persons = st.selectbox('persons', df['persons'].unique())
lug_boot = st.selectbox('lug_boot', df['lug_boot'].unique())
safety = st.selectbox('safety', df['safety'].unique())

# Predict class
 features = [df['class'] = df['class'].map({'unacc':0, 'acc':1, 'good':2, 'vgood':3})
df['buying']=df['buying'].map({'low':0, 'med':1, 'high':2, 'vhigh':3})
df['maint']=df['maint'].map({'low':0, 'med':1, 'high':2, 'vhigh':3})
df['doors']=df['doors'].map({'2':0, '3':1, '4':2, '5more':3})
df['persons']=df['persons'].map({'2':0, '4':1, 'more':2})
df['lug_boot']=df['lug_boot'].map({'small':0, 'med':1, 'big':2})
df['safety']=df['safety'].map({'low':0, 'med':1, 'high':2})]
    features = np.array([features]) # Convert to a NumPy array

prediction = model.predict(features)[0]
prediction_prob = model.predict_proba(features)

st.write(f"### Predicted class: **{prediction.capitalize()}**")
st.write(f"### Prediction Probability: ")
st.write(f"unacc: {prediction_prob[0][0]:.2f}, acc: {prediction_prob[0][1]:.2f}, good: {prediction_prob[0][2]:.2f}, vgood: {prediction_prob[0][3]:.2f}")

st.write("### About the App:")
st.write("This app uses Multinomial Logistic Regression (Softmax) trained on the car dataset to classify evaluation into four classes: unacc, acc, good, vgood.")

st.write("Made by Ruchita 😀")

